#########################################
# ___  ___       ______  _         _
# |  \/  |       | ___ \| |       | |
# | .  . | _   _ | |_/ /| |  ___  | |_
# | |\/| || | | ||  __/ | | / _ \ | __|
# | |  | || |_| || |    | || (_) || |_
# \_|  |_/ \__, |\_|    |_| \___/  \__|
#           __/ |
#          |___/
#
#########################################


# The language that should be used in MyPlot
# Available languages: eng, nl, vi, spa, chs, zho
#
# English language pack by @Exxarion
# Dutch language pack by @Wies
# Vietnamese language pack by @daany123
# Spanish language pack by @thelucyclub
# Chinese ( ROC ) pack by @jerryzooyoyo
# Chinese ( PRC ) pack by @jerryzooyoyo

language: eng

# The data provider where plot data is stored.
# There is currently only one data provider: sqlite.
DataProvider: sqlite

# Use an economy with MyPlot. This will allow for plot pricing such as claiming, clearing, etc.
# Currently supported economy plugins: Economy$, PocketMoney
# MyPlot will use any economy plugin found on the server.
# Be sure not to use more than 1 economy plugin!
UseEconomy: false

# Amount of plots to be cached.
# Increasing this number might improve performance, but also increase memory usage.
PlotCacheSize: 564

# When a player enters a plot, a popup with basic info will be shown
ShowPlotPopup: true

# Amount of blocks to reset per tick.
# Increasing this number will speed up '/p clear' and '/p reset' but also increases lag
ClearBlocksPerTick: 986


# These settings will be used when creating a new world.
DefaultWorld:

  # Restrict entities (e.g. tnt) from moving except falling
  # This will prevent things like tnt cannons from ruining other plots
  RestrictEntityMovement: true

  # How much it costs to claim a plot (Economy must be set to 'true')
  ClaimPrice: 100
  # How much it costs to clear a plot (Economy must be set to 'true')
  ClearPrice: 45
  # How much it costs to dispose a plot (Economy must be set to 'true')
  DisposePrice: 0
  # How much it costs to reset a plot (Economy must be set to 'true')
  ResetPrice: 0

  # The size of a plot
  PlotSize: 24
  # The height of a plot
  GroundHeight: 64
  # The width of the road
  RoadWidth: 7

  # The block that the road is made of (Default is Oak Planks)
  RoadBlock: '173:0'
  # The block that plot walls are made of (Default is Stone Slabs)
  WallBlock: '44:0'
  # The block used as the plot floor (Default is Grass)
  PlotFloorBlock: '1:0'
  # The block that fills the rest of the plot (Default is Dirt)
  PlotFillBlock: '3:0'
  # The block at the bottom (Default is Bedrock)
  BottomBlock: '7:0'
