---
name: LaunchPad
main: hoyinm14mc\launchpad\LaunchPad
api:
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
version: 1.0.1
author: hoyinm14mc
commands:
  launchpad:
    usage: /launchpad create|destroy|version
    permission: launchpad.command
    description: LaunchPad command
    aliases:
    - lpad
    - launchp
permissions:
  launchpad.command:
    default: op
  launchpad.use:
    default: true
  launchpad.create:
    default: op
  launchpad.destroy:
    default: op
...
