---
name: Nicks
version: 0.0.1
main: \nicks\Main
authors:
- Jack Noordhuis
api:
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
permissions:
  nick:
    description: Nick master permission node
    default: op
    children:
      nick.command:
        description: Nick master command permission node
        default: op
        children:
          nick.command.set:
            description: SetNick command permission node
            default: op
          nick.command.remove:
            description: RemoveNick command permission node
            default: op
commands:
  nick:
    description: Nick command
    usage: 'Usage: /nick <set|remove> <player> <nick>'
    permission: nick.command
...
