---
name: BuyCraft
main: buycraft\BuyCraft
version: 1.2.2
author: Falkirks
api:
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
load: POSTWORLD
permissions:
  buycraft:
    default: op
    description: Top level BuyCraft permission
    children:
      buycraft.admin:
        default: op
      buycraft.buy:
        default: true
...
