---
name: EconomyShop
version: 2.0.7
api:
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
main: onebone\economyshop\EconomyShop
author: onebone
depend:
- EconomyAPI
permissions:
  economyshop.*:
    description: Allows all functions in EconomyShop
    default: op
    children:
      economyshop.shop.*:
        description: Allows all functions about shops
        default: op
        children:
          economyshop.shop.buy:
            description: Allows player to buy from shop
            default: true
          economyshop.shop.create:
            description: Allows player to create shop
            default: op
          economyshop.shop.remove:
            description: Allows player to remove shop
            default: op
...
