name: MineReset
main: falkirks\minereset\MineReset
version: 3.0
author: Falk
api: [1.0.0, 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5]
load: POSTWORLD
permissions:
 minereset:
  default: op
  children:
   minereset.command:
    default: op
    description: Use MineReset commands
    children:
      minereset.command.about:
        description: Read the about text
      minereset.command.create:
        description: Add new Mines
      minereset.command.set:
        description: Set existing mines
      minereset.command.reset:
        description: Reset mines
      minereset.command.destroy:
        description: Remove mines
      minereset.command.resetall:
        description: Reset all mines