---
name: AdvancedKits
main: AdvancedKits\Main
version: 5.100000
api:
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
author: luca28pet
description: Add kits to your server
website: https://github.com/luca28pet/AdvancedKits
commands:
  kit:
    description: Get a kit!
    usage: /kit <kitName>
    aliases:
    - ak
    - advancedkits
    permission: advancedkits.command
  akreload:
    descrpition: Reload Kits settings
    usage: /akreload
    permission: advancedkits.admin
permissions:
  advancedkits.command:
    description: Allows the user to run /kit command
    default: true
  advancedkits.admin:
    description: Allows to manage admin features
    default: op
...
