---
name: SimpleWarp
main: falkirks\simplewarp\SimpleWarp
version: 2.1.0
author: Falkirks
api:
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
load: POSTWORLD
softdepend:
- FastTransfer
- SlowTransfer
- EssentialsPE
permissions:
  simplewarp:
    default: op
    children:
      simplewarp.command:
        default: op
        children:
          simplewarp.command.list:
            default: true
            children:
              simplewarp.command.list.xyz:
                default: op
              simplewarp.command.list.visual:
                default: op
          simplewarp.command.addwarp:
            default: op
          simplewarp.command.delwarp:
            default: op
          simplewarp.command.warp:
            default: true
            children:
              simplewarp.command.warp.other:
                default: op
          simplewarp.command.openwarp:
            default: op
          simplewarp.command.closewarp:
            default: op
      simplewarp.essentials.notice:
        default: op
        description: Recieve messages when their is warp conflict in Essentials
      simplewarp.warp:
        default: op
        description: Allows usage of all warps
...
