---
name: Crates
author: Jack Noordhuis
version: 1-Beta
description: Advanced Crate plugin for Conflict
main: crates\Main
api:
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
commands:
  givekey:
    description: Gives a player the specified crate key
    usage: /givekey <player> <key id> <amount>
permissions:
  crates:
    description: Main crates permission
    default: op
    children:
      crates.command:
        description: Main crates command permission
        default: op
        children:
          crates.command.givekey:
            description: Permission for /givekey command
            default: op
...
