---
name: supertext
main: supertext\supertext
version: 1
api:
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
load: POSTWORLD
author: FXXK
commands:
  Atext:
    default: op
    description: A type text
    useage: /atext
    permission: supertext.command.Atext
  Btext:
    default: op
    description: B type text
    useage: /btext
    permission: supertext.command.Btext
permissions:
  supertext.*:
    description: 根权限
    default: op
  supertext.command.*:
    description: 命令使用权限
    default: op
  supertext.command.Atext:
    description: permissionaaa
    default: op
  supertext.command.Btext:
    description: permissionbbb
    default: op
...
