---
name: ClearLagg
main: ClearLagg\Loader
version: 1.1.0
api:
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
author: LegendOfMCPE
website: https://github.com/LegendOfMCPE/ClearLagg
description: Port of Bukkit ClearLagg for PocketMine Servers
permissions:
  clearlagg:
    default: false
    description: Allows access to all ClearLagg features.
    children:
      clearlagg.command:
        default: false
        description: Allows access to all ClearLagg commands.
        children:
          clearlagg.command.clearlagg:
            default: op
            description: Allows access to the clearlagg command.
...
