---
name: TimeCommander
main: LDX\TimeCommander\Main
version: 2.100000
api:
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
author: LDX
load: POSTWORLD
website: https://github.com/LDX-MCPE/TimeCommander
...
