---
name: CombatLogger
version: 1.2.0
api:
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
author: Lambo
main: Lambo\CombatLogger\Main
description: Stop players from logging out during a fight
...
