---
name: VoteReward
main: LDX\VoteReward\Main
version: 3.0.2
api:
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
author: LDX
website: http://votereward.mcpe.me
load: POSTWORLD
commands:
  vote:
    usage: /vote
    description: Checks to see if you've voted yet.
    permission: votereward.command.vote
permissions:
  votereward:
    default: false
    description: Allows access to all VoteReward features.
    children:
      votereward.command:
        default: false
        description: Allows access to all VoteReward commands.
        children:
          votereward.command.vote:
            default: true
            description: Allows access to using the vote command.
          votereward.command.reload:
            default: op
            description: Allows access to the vote reload subcommand.
...
